// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmazzulvpruduaulobec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtYXp6dWx2cHJ1ZHVhdWxvYmVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxMDU1MjAsImV4cCI6MjA1MTY4MTUyMH0.HZbs_e8PV_1vo0qFHjo2kc-q9AUTqNAov52ScvGNguU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);